/** Content type constants, as docx4j org.docx4j.openpackaging.contenttype.ContentTypes. */
export const ContentTypes = {
  CONTENT_TYPES_PART: 'application/vnd.openxmlformats-package.content-types+xml',
  RELATIONSHIPS_PART: 'application/vnd.openxmlformats-package.relationships+xml',
  APPLICATION_XML: 'application/xml',
  XML: 'text/xml',
  PACKAGE_COREPROPERTIES: 'application/vnd.openxmlformats-package.core-properties+xml',
  OFFICEDOCUMENT_CUSTOMPROPERTIES: 'application/vnd.openxmlformats-officedocument.custom-properties+xml',
  OFFICEDOCUMENT_EXTENDEDPROPERTIES: 'application/vnd.openxmlformats-officedocument.extended-properties+xml',
  OFFICEDOCUMENT_CUSTOMXML_DATASTORAGEPROPERTIES: 'application/vnd.openxmlformats-officedocument.customXmlProperties+xml',
  OFFICEDOCUMENT_CUSTOMXML_DATASTORAGE: 'application/xml',
  OFFICEDOCUMENT_THEME: 'application/vnd.openxmlformats-officedocument.theme+xml',
  OFFICEDOCUMENT_THEME_OVERRIDE: 'application/vnd.openxmlformats-officedocument.themeOverride+xml',
  OFFICEDOCUMENT_FONT: 'application/vnd.openxmlformats-officedocument.obfuscatedFont',
  TRUETYPE_FONT: 'application/x-font-ttf',
  OFFICEDOCUMENT_VBA_PROJECT: 'application/vnd.ms-office.vbaProject',
  OFFICEDOCUMENT_VBA_DATA: 'application/vnd.ms-word.vbaData+xml',
  OFFICEDOCUMENT_VBA_PROJECT_SIGNATURE: 'application/vnd.ms-office.vbaProjectSignature',
  OFFICEDOCUMENT_OLE_OBJECT: 'application/vnd.openxmlformats-officedocument.oleObject',
  OFFICEDOCUMENT_ACTIVEX_OBJECT: 'application/vnd.ms-office.activeX',
  OFFICEDOCUMENT_ACTIVEX_XML_OBJECT: 'application/vnd.ms-office.activeX+xml',
  WEB_EXTENSION_TASKPANES: 'application/vnd.ms-office.webextensiontaskpanes+xml',
  WEB_EXTENSION_WEBEXTENSION: 'application/vnd.ms-office.webextension+xml',
  WORDPROCESSINGML_DOCUMENT: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml',
  WORDPROCESSINGML_DOCUMENT_MACROENABLED: 'application/vnd.ms-word.document.macroEnabled.main+xml',
  WORDPROCESSINGML_TEMPLATE: 'application/vnd.openxmlformats-officedocument.wordprocessingml.template.main+xml',
  WORDPROCESSINGML_TEMPLATE_MACROENABLED: 'application/vnd.ms-word.template.macroEnabledTemplate.main+xml',
  WORDPROCESSINGML_COMMENTS: 'application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml',
  WORDPROCESSINGML_COMMENTS_EXTENDED: 'application/vnd.openxmlformats-officedocument.wordprocessingml.commentsExtended+xml',
  WORDPROCESSINGML_COMMENTS_IDS: 'application/vnd.openxmlformats-officedocument.wordprocessingml.commentsIds+xml',
  WORDPROCESSINGML_COMMENTS_EXTENSIBLE: 'application/vnd.openxmlformats-officedocument.wordprocessingml.commentsExtensible+xml',
  WORDPROCESSINGML_ENDNOTES: 'application/vnd.openxmlformats-officedocument.wordprocessingml.endnotes+xml',
  WORDPROCESSINGML_FONTTABLE: 'application/vnd.openxmlformats-officedocument.wordprocessingml.fontTable+xml',
  WORDPROCESSINGML_FOOTER: 'application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml',
  WORDPROCESSINGML_FOOTNOTES: 'application/vnd.openxmlformats-officedocument.wordprocessingml.footnotes+xml',
  WORDPROCESSINGML_GLOSSARYDOCUMENT: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document.glossary+xml',
  WORDPROCESSINGML_HEADER: 'application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml',
  MS_WORD_KEYMAP: 'application/vnd.ms-word.keyMapCustomizations+xml',
  WORDPROCESSINGML_NUMBERING: 'application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml',
  WORDPROCESSINGML_PEOPLE: 'application/vnd.openxmlformats-officedocument.wordprocessingml.people+xml',
  WORDPROCESSINGML_SETTINGS: 'application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml',
  WORDPROCESSINGML_STYLES: 'application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml',
  WORDPROCESSINGML_STYLESWITHEFFECTS: 'application/vnd.ms-word.stylesWithEffects+xml',
  WORDPROCESSINGML_WEBSETTINGS: 'application/vnd.openxmlformats-officedocument.wordprocessingml.webSettings+xml',
  DRAWINGML_DIAGRAM_DATA: 'application/vnd.openxmlformats-officedocument.drawingml.diagramData+xml',
  DRAWINGML_DIAGRAM_LAYOUT: 'application/vnd.openxmlformats-officedocument.drawingml.diagramLayout+xml',
  DRAWINGML_DIAGRAM_COLORS: 'application/vnd.openxmlformats-officedocument.drawingml.diagramColors+xml',
  DRAWINGML_DIAGRAM_STYLE: 'application/vnd.openxmlformats-officedocument.drawingml.diagramStyle+xml',
  DRAWINGML_DIAGRAM_LAYOUT_HEADER: 'application/vnd.openxmlformats-officedocument.drawingml.diagramLayoutHeader+xml',
  DRAWINGML_DIAGRAM_DRAWING: 'application/vnd.ms-office.drawingml.diagramDrawing+xml',
  DRAWINGML_CHART: 'application/vnd.openxmlformats-officedocument.drawingml.chart+xml',
  DRAWINGML_DRAWING: 'application/vnd.openxmlformats-officedocument.drawing+xml',
  DRAWINGML_CHART_SHAPES: 'application/vnd.openxmlformats-officedocument.drawingml.chartshapes+xml',
  CHART_EX: 'application/vnd.ms-office.chartex+xml',
  CHART_STYLE: 'application/vnd.ms-office.chartstyle+xml',
  CHART_COLOR_STYLE: 'application/vnd.ms-office.chartcolorstyle+xml',
  VML_DRAWING: 'application/vnd.openxmlformats-officedocument.vmlDrawing',
  PRESENTATION: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  PRESENTATIONML_MAIN: 'application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml',
  PRESENTATIONML_MACROENABLED: 'application/vnd.ms-powerpoint.presentation.macroEnabled.main+xml',
  PRESENTATIONML_TEMPLATE: 'application/vnd.openxmlformats-officedocument.presentationml.template.main+xml',
  PRESENTATIONML_TEMPLATE_MACROENABLED: 'application/vnd.ms-powerpoint.template.macroEnabled.main+xml',
  PRESENTATIONML_SLIDESHOW: 'application/vnd.openxmlformats-officedocument.presentationml.slideshow.main+xml',
  PRESENTATIONML_COMMENTS: 'application/vnd.openxmlformats-officedocument.presentationml.comments+xml',
  PRESENTATIONML_COMMENT_AUTHORS: 'application/vnd.openxmlformats-officedocument.presentationml.commentAuthors+xml',
  PRESENTATIONML_FONT_DATA: 'application/x-fontdata',
  PRESENTATIONML_SLIDE: 'application/vnd.openxmlformats-officedocument.presentationml.slide+xml',
  PRESENTATIONML_SLIDE_MASTER: 'application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml',
  PRESENTATIONML_SLIDE_LAYOUT: 'application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml',
  PRESENTATIONML_TABLE_STYLES: 'application/vnd.openxmlformats-officedocument.presentationml.tableStyles+xml',
  PRESENTATIONML_PRES_PROPS: 'application/vnd.openxmlformats-officedocument.presentationml.presProps+xml',
  PRESENTATIONML_VIEW_PROPS: 'application/vnd.openxmlformats-officedocument.presentationml.viewProps+xml',
  PRESENTATIONML_TAGS: 'application/vnd.openxmlformats-officedocument.presentationml.tags+xml',
  PRESENTATIONML_NOTES_SLIDE: 'application/vnd.openxmlformats-officedocument.presentationml.notesSlide+xml',
  PRESENTATIONML_NOTES_MASTER: 'application/vnd.openxmlformats-officedocument.presentationml.notesMaster+xml',
  PRESENTATIONML_HANDOUT_MASTER: 'application/vnd.openxmlformats-officedocument.presentationml.handoutMaster+xml',
  SPREADSHEETML_WORKBOOK: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml',
  SPREADSHEETML_WORKBOOK_MACROENABLED: 'application/vnd.ms-excel.sheet.macroEnabled.main+xml',
  SPREADSHEETML_TEMPLATE: 'application/vnd.openxmlformats-officedocument.spreadsheetml.template.main+xml',
  SPREADSHEETML_TEMPLATE_MACROENABLED: 'application/vnd.ms-excel.template.macroEnabled.main+xml',
  SPREADSHEETML_PRINTER_SETTINGS: 'application/vnd.openxmlformats-officedocument.spreadsheetml.printerSettings',
  SPREADSHEETML_STYLES: 'application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml',
  SPREADSHEETML_WORKSHEET: 'application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml',
  SPREADSHEETML_CHARTSHEET: 'application/vnd.openxmlformats-officedocument.spreadsheetml.chartsheet+xml',
  SPREADSHEETML_CALC_CHAIN: 'application/vnd.openxmlformats-officedocument.spreadsheetml.calcChain+xml',
  SPREADSHEETML_SHARED_STRINGS: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml',
  SPREADSHEETML_PIVOT_CACHE_DEFINITION: 'application/vnd.openxmlformats-officedocument.spreadsheetml.pivotCacheDefinition+xml',
  SPREADSHEETML_PIVOT_CACHE_RECORDS: 'application/vnd.openxmlformats-officedocument.spreadsheetml.pivotCacheRecords+xml',
  SPREADSHEETML_PIVOT_TABLE: 'application/vnd.openxmlformats-officedocument.spreadsheetml.pivotTable+xml',
  SPREADSHEETML_QUERY_TABLE: 'application/vnd.openxmlformats-officedocument.spreadsheetml.queryTable+xml',
  SPREADSHEETML_TABLE: 'application/vnd.openxmlformats-officedocument.spreadsheetml.table+xml',
  SPREADSHEETML_COMMENTS: 'application/vnd.openxmlformats-officedocument.spreadsheetml.comments+xml',
  SPREADSHEETML_CONNECTIONS: 'application/vnd.openxmlformats-officedocument.spreadsheetml.connections+xml',
  SPREADSHEETML_EXTERNAL_LINK: 'application/vnd.openxmlformats-officedocument.spreadsheetml.externalLink+xml',
  DIGITAL_SIGNATURE_ORIGIN_PART: 'application/vnd.openxmlformats-package.digital-signature-origin',
  DIGITAL_SIGNATURE_XML_SIGNATURE_PART: 'application/vnd.openxmlformats-package.digital-signature-xmlsignature+xml',
  INK_ML: 'application/inkml+xml',
  IMAGE_EMF: 'image/x-emf',
  IMAGE_EMF2: 'image/emf',
  IMAGE_WMF: 'image/x-wmf',
  IMAGE_GIF: 'image/gif',
  IMAGE_JPEG: 'image/jpeg',
  IMAGE_JPEG_XR: 'image/vnd.ms-photo',
  IMAGE_PICT: 'image/pict',
  IMAGE_PNG: 'image/png',
  IMAGE_X_PNG: 'image/x-png',
  IMAGE_TIFF: 'image/tiff',
  IMAGE_WEBP: 'image/webp',
  IMAGE_EPS: 'application/postscript',
  IMAGE_BMP: 'image/bmp',
  IMAGE_SVG: 'image/svg+xml',
  OCTET_STREAM: 'application/octet-stream',
} as const;

/** Content type by lower-case file extension for the image kinds the object model relates to. */
export const IMAGE_CONTENT_TYPES_BY_EXTENSION: Readonly<Record<string, string>> = {
  png: ContentTypes.IMAGE_PNG,
  jpg: ContentTypes.IMAGE_JPEG,
  jpeg: ContentTypes.IMAGE_JPEG,
  gif: ContentTypes.IMAGE_GIF,
  bmp: ContentTypes.IMAGE_BMP,
  tif: ContentTypes.IMAGE_TIFF,
  tiff: ContentTypes.IMAGE_TIFF,
  emf: ContentTypes.IMAGE_EMF,
  wmf: ContentTypes.IMAGE_WMF,
  svg: ContentTypes.IMAGE_SVG,
  webp: ContentTypes.IMAGE_WEBP,
  wdp: ContentTypes.IMAGE_JPEG_XR,
  eps: ContentTypes.IMAGE_EPS,
};

/** Whether bytes of this content type are XML (parsed to a DOM when the registry has no typed part). */
export function isXmlContentType(contentType: string | undefined): boolean {
  if (contentType === undefined) return false;
  return contentType.endsWith('+xml') || contentType === ContentTypes.APPLICATION_XML || contentType === ContentTypes.XML;
}

/** Already-compressed media, stored rather than deflated in a zip (docx4j ZipPartStore.shouldCompress). */
export function isStoredUncompressed(contentType: string | undefined): boolean {
  return contentType === ContentTypes.IMAGE_PNG || contentType === ContentTypes.IMAGE_X_PNG
    || contentType === ContentTypes.IMAGE_JPEG || contentType === ContentTypes.IMAGE_GIF;
}
