/** Relationship types and namespaces, as docx4j org.docx4j.openpackaging.parts.relationships.Namespaces. */
export const Namespaces = {
  CONTENT_TYPES: 'http://schemas.openxmlformats.org/package/2006/content-types',
  RELATIONSHIPS: 'http://schemas.openxmlformats.org/package/2006/relationships',
  RELATIONSHIPS_OFFICEDOC: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships',
  NS_WORD12: 'http://schemas.openxmlformats.org/wordprocessingml/2006/main',
  PKG_XML: 'http://schemas.microsoft.com/office/2006/xmlPackage',
  MARKUP_COMPATIBILITY: 'http://schemas.openxmlformats.org/markup-compatibility/2006',

  DIGITAL_SIGNATURE: 'http://schemas.openxmlformats.org/package/2006/relationships/digital-signature/signature',
  DIGITAL_SIGNATURE_CERTIFICATE: 'http://schemas.openxmlformats.org/package/2006/relationships/digital-signature/certificate',
  DIGITAL_SIGNATURE_ORIGIN: 'http://schemas.openxmlformats.org/package/2006/relationships/digital-signature/origin',
  PROPERTIES_CORE: 'http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties',
  PROPERTIES_EXTENDED: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties',
  PROPERTIES_CUSTOM: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/custom-properties',
  PROPERTIES_COVERPAGE: 'http://schemas.microsoft.com/office/2006/coverPageProps',
  IMAGE: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/image',
  THUMBNAIL: 'http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail',
  METADATA_THUMBNAIL: 'http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail',
  DOCUMENT: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument',
  DOCUMENT_STRICT: 'http://purl.oclc.org/ooxml/officeDocument/relationships/officeDocument',
  HYPERLINK: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink',
  CUSTOM_XML_DATA_STORAGE: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/customXml',
  CUSTOM_XML_DATA_STORAGE_PROPERTIES: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/customXmlProps',
  WEB_SETTINGS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings',
  SETTINGS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings',
  STYLES: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles',
  THEME: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme',
  THEME_OVERRIDE: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/themeOverride',
  FONT_TABLE: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable',
  FONT: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/font',
  HEADER: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/header',
  FOOTER: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer',
  GLOSSARY_DOCUMENT: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/glossaryDocument',
  NUMBERING: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering',
  FOOTNOTES: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/footnotes',
  ENDNOTES: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/endnotes',
  COMMENTS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments',
  COMMENTS_EXTENDED: 'http://schemas.microsoft.com/office/2011/relationships/commentsExtended',
  COMMENTS_IDS: 'http://schemas.microsoft.com/office/2016/09/relationships/commentsIds',
  COMMENTS_EXTENSIBLE: 'http://schemas.microsoft.com/office/2018/08/relationships/commentsExtensible',
  OFFICE_2011_PEOPLE: 'http://schemas.microsoft.com/office/2011/relationships/people',
  AF: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/aFChunk',
  SUBDOCUMENT: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/subDocument',
  ATTACHED_TEMPLATE: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/attachedTemplate',
  VBA_PROJECT: 'http://schemas.microsoft.com/office/2006/relationships/vbaProject',
  VBA_DATA_WORD: 'http://schemas.microsoft.com/office/2006/relationships/wordVbaData',
  KEYMAP: 'http://schemas.microsoft.com/office/2006/relationships/keyMapCustomizations',
  VBA_PROJECT_SIGNATURE: 'http://schemas.microsoft.com/office/2006/relationships/vbaProjectSignature',
  OLE_OBJECT: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/oleObject',
  EMBEDDED_PKG: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/package',
  ACTIVEX_XML_OBJECT: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/control',
  VML: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/vmlDrawing',
  CHART_EX: 'http://schemas.microsoft.com/office/2014/relationships/chartEx',
  CHART_COLOR_STYLE: 'http://schemas.microsoft.com/office/2011/relationships/chartColorStyle',
  CHART_STYLE: 'http://schemas.microsoft.com/office/2011/relationships/chartStyle',
  DRAWINGML_DIAGRAM_DATA: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/diagramData',
  DRAWINGML_DIAGRAM_LAYOUT: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/diagramLayout',
  DRAWINGML_DIAGRAM_COLORS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/diagramColors',
  DRAWINGML_DIAGRAM_STYLE: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/diagramQuickStyle',
  DRAWINGML_DIAGRAM_LAYOUT_HEADER: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/diagramLayoutHeader',
  DRAWINGML_DIAGRAM_DRAWING: 'http://schemas.microsoft.com/office/2007/relationships/diagramDrawing',
  PRESENTATIONML_COMMENTS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments',
  PRESENTATIONML_COMMENT_AUTHORS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/commentAuthors',
  PRESENTATIONML_FONT_DATA: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/font',
  PRESENTATIONML_MAIN: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument',
  PRESENTATIONML_SLIDE: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide',
  PRESENTATIONML_SLIDE_MASTER: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster',
  PRESENTATIONML_SLIDE_LAYOUT: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout',
  PRESENTATIONML_TABLE_STYLES: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/tableStyles',
  PRESENTATIONML_PRES_PROPS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/presProps',
  PRESENTATIONML_VIEW_PROPS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/viewProps',
  PRESENTATIONML_TAGS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/tags',
  PRESENTATIONML_NOTES_SLIDE: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesSlide',
  PRESENTATIONML_NOTES_MASTER: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/notesMaster',
  PRESENTATIONML_HANDOUT_MASTER: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/handoutMaster',
  SPREADSHEETML_WORKBOOK: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument',
  SPREADSHEETML_WORKSHEET: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet',
  SPREADSHEETML_CHARTSHEET: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/chartsheet',
  SPREADSHEETML_PRINTER_SETTINGS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/printerSettings',
  SPREADSHEETML_CALC_CHAIN: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/calcChain',
  SPREADSHEETML_SHARED_STRINGS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings',
  SPREADSHEETML_STYLES: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles',
  SPREADSHEETML_DRAWING: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/drawing',
  SPREADSHEETML_CHART: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/chart',
  CHART_USER_SHAPES: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/chartUserShapes',
  SPREADSHEETML_COMMENTS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments',
  SPREADSHEETML_PIVOT_TABLE: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/pivotTable',
  SPREADSHEETML_QUERY_TABLE: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/queryTable',
  SPREADSHEETML_TABLE: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/table',
  SPREADSHEETML_CONNECTIONS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/connections',
  SPREADSHEETML_PIVOT_CACHE_DEFINITION: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/pivotCacheDefinition',
  SPREADSHEETML_PIVOT_CACHE_RECORDS: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/pivotCacheRecords',
  SPREADSHEETML_EXTERNAL_LINK: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/externalLink',
  // The Excel 2010 and 2013 extension parts (CR-004): slicers and their caches are 2007,
  // timelines 2011, the survey 2010; the rest are the officeDocument ones.
  /** `/xl/slicerCaches/slicerCache1.xml`, from the workbook. */
  SPREADSHEETML_SLICER_CACHE: 'http://schemas.microsoft.com/office/2007/relationships/slicerCache',
  /** `/xl/slicers/slicer1.xml`, from a worksheet. */
  SPREADSHEETML_SLICERS: 'http://schemas.microsoft.com/office/2007/relationships/slicer',
  /** `/xl/timelineCaches/timelineCache1.xml`, from the workbook. */
  SPREADSHEETML_TIMELINE_CACHE: 'http://schemas.microsoft.com/office/2011/relationships/timelineCache',
  /** `/xl/timelines/timeline1.xml`, from a worksheet. */
  SPREADSHEETML_TIMELINES: 'http://schemas.microsoft.com/office/2011/relationships/timeline',
  /** `/xl/ctrlProps/ctrlProp1.xml`, from a worksheet, for one of its form controls. */
  SPREADSHEETML_CONTROL_PROPERTIES: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/ctrlProp',
  /** `/xl/customDataProps/customDataProps1.xml`, from the workbook. */
  SPREADSHEETML_CUSTOM_DATA_PROPERTIES: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/customDataProps',
  /** `/xl/customData/customData1.dat`, from its properties part. */
  SPREADSHEETML_CUSTOM_DATA: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/customData',
  /** `/xl/surveys/survey1.xml`, from the workbook. */
  SPREADSHEETML_SURVEY: 'http://schemas.microsoft.com/office/2010/relationships/Survey',
  /** `/xl/model/item.data` ([MS-XLDM]), from the workbook. */
  SPREADSHEETML_DATA_MODEL: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/powerPivotData',
  WEB_EXTENSION_TASKPANES: 'http://schemas.microsoft.com/office/webextensions/taskpanes/2010/11',
  WEB_EXTENSION_WEBEXTENSION: 'http://schemas.microsoft.com/office/webextensions/webextension/2010/11',
  XML_EVENTS: 'http://www.w3.org/2001/xml-events',
  XFORMS: 'http://www.w3.org/2002/xforms',
  XML_SCHEMA: 'http://www.w3.org/2001/XMLSchema',
} as const;
